export const movieTypes = [
  "Action",
  "Adventure",
  "Animation",
  "Children's",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Film-Noir",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
  "Western"
];

export const movies = [
  {
    title: "The Shawshank Redemption",
    rate: 9.3,
    year: 1994,
    image: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
  },
  {
    title: "The Godfather",
    rate: 9.2,
    year: 1972,
    image: "https://m.media-amazon.com/images/I/51rggtPgmRL._AC_.jpg",
  },
  {
    title: "The Dark Knight",
    rate: 9.0,
    year: 2008,
    image: "https://m.media-amazon.com/images/I/51zUbui+gbL._AC_.jpg",
  },
  {
    title: "The Godfather Part II",
    rate: 9.0,
    year: 1974,
    image: "https://m.media-amazon.com/images/I/41uT8W2+0zL._AC_.jpg",
  },
  {
    title: "12 Angry Men",
    rate: 9.0,
    year: 1957,
    image: "https://m.media-amazon.com/images/I/51Y0gK2y2CL._AC_.jpg",
  },
  {
    title: "Schindler's List",
    rate: 8.9,
    year: 1993,
    image: "https://m.media-amazon.com/images/I/51RjGZJx+dL._AC_.jpg",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    rate: 8.9,
    year: 2003,
    image: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
  },
  {
    title: "Pulp Fiction",
    rate: 8.9,
    year: 1994,
    image: "https://m.media-amazon.com/images/I/51oBxmV-dML._AC_.jpg",
  },
  {
    title: "The Good, the Bad and the Ugly",
    rate: 8.8,
    year: 1966,
    image: "https://m.media-amazon.com/images/I/51NpxXay6ML._AC_.jpg",
  },
  {
    title: "Forrest Gump",
    rate: 8.8,
    year: 1994,
    image: "https://m.media-amazon.com/images/I/41c9f7n1rxL._AC_.jpg",
  },
  {
    title: "Fight Club",
    rate: 8.8,
    year: 1999,
    image: "https://m.media-amazon.com/images/I/51v5ZpFyaFL._AC_.jpg",
  },
  {
    title: "Inception",
    rate: 8.8,
    year: 2010,
    image: "https://m.media-amazon.com/images/I/5101wIl6s9L._AC_.jpg",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    rate: 8.8,
    year: 2001,
    image: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    rate: 8.7,
    year: 1980,
    image: "https://m.media-amazon.com/images/I/51Ta3MxoJGL._AC_.jpg",
  },
  {
    title: "The Matrix",
    rate: 8.7,
    year: 1999,
    image: "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
  },
  {
    title: "Goodfellas",
    rate: 8.7,
    year: 1990,
    image: "https://m.media-amazon.com/images/I/51Z2yqKUT1L._AC_.jpg",
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    rate: 8.7,
    year: 1975,
    image: "https://m.media-amazon.com/images/I/51j0v0rr9nL._AC_.jpg",
  },
  {
    title: "Se7en",
    rate: 8.6,
    year: 1995,
    image: "https://m.media-amazon.com/images/I/51K8ouYrHeL._AC_.jpg",
  },
  {
    title: "It's a Wonderful Life",
    rate: 8.6,
    year: 1946,
    image: "https://m.media-amazon.com/images/I/51QWYcEV4oL._AC_.jpg",
  },
  {
    title: "Seven Samurai",
    rate: 8.6,
    year: 1954,
    image: "https://m.media-amazon.com/images/I/51f7JwYpAHL._AC_.jpg",
  },
  {
    title: "The Silence of the Lambs",
    rate: 8.6,
    year: 1991,
    image: "https://m.media-amazon.com/images/I/41GVdcKjP1L._AC_.jpg",
  },
  {
    title: "Saving Private Ryan",
    rate: 8.6,
    year: 1998,
    image: "https://m.media-amazon.com/images/I/51s+fbRz1DL._AC_.jpg",
  },
  {
    title: "Interstellar",
    rate: 8.6,
    year: 2014,
    image: "https://m.media-amazon.com/images/I/71y7e2ujlDL._AC_SL1111_.jpg",
  },
  {
    title: "The Green Mile",
    rate: 8.6,
    year: 1999,
    image: "https://m.media-amazon.com/images/I/51CkWzPjeWL._AC_.jpg",
  },
  {
    title: "City of God",
    rate: 8.6,
    year: 2002,
    image: "https://m.media-amazon.com/images/I/51A-4aTQqjL._AC_.jpg",
  },
  {
    title: "Life Is Beautiful",
    rate: 8.6,
    year: 1997,
    image: "https://m.media-amazon.com/images/I/51UZSElW+hL._AC_.jpg",
  },
  {
    title: "The Usual Suspects",
    rate: 8.5,
    year: 1995,
    image: "https://m.media-amazon.com/images/I/51yr2iBT0TL._AC_.jpg",
  },
  {
    title: "Léon: The Professional",
    rate: 8.5,
    year: 1994,
    image: "https://m.media-amazon.com/images/I/51N0Z1fjsyL._AC_.jpg",
  },
  {
    title: "The Lion King",
    rate: 8.5,
    year: 1994,
    image: "https://m.media-amazon.com/images/I/51F9CKo19kL._AC_.jpg",
  },
  {
    title: "Back to the Future",
    rate: 8.5,
    year: 1985,
    image: "https://m.media-amazon.com/images/I/51OD-KOK2-L._AC_.jpg",
  },
  {
    title: "The Pianist",
    rate: 8.5,
    year: 2002,
    image: "https://m.media-amazon.com/images/I/51KM9yZTwFL._AC_.jpg",
  },
  {
    title: "Terminator 2: Judgment Day",
    rate: 8.5,
    year: 1991,
    image: "https://m.media-amazon.com/images/I/61MCSO5Q+dL._AC_SL1024_.jpg",
  },
  {
    title: "American History X",
    rate: 8.5,
    year: 1998,
    image: "https://m.media-amazon.com/images/I/51Sn8PEXwcL._AC_.jpg",
  },
  {
    title: "Gladiator",
    rate: 8.5,
    year: 2000,
    image: "https://m.media-amazon.com/images/I/51A6lUdWnFL._AC_.jpg",
  },
  {
    title: "The Departed",
    rate: 8.5,
    year: 2006,
    image: "https://m.media-amazon.com/images/I/51gRDMN1J+L._AC_.jpg",
  },
  {
    title: "Whiplash",
    rate: 8.5,
    year: 2014,
    image: "https://m.media-amazon.com/images/I/51pYpZ5nGIL._AC_.jpg",
  },
  {
    title: "The Prestige",
    rate: 8.5,
    year: 2006,
    image: "https://m.media-amazon.com/images/I/51dr3mGPa6L._AC_.jpg",
  },
  {
    title: "The Intouchables",
    rate: 8.5,
    year: 2011,
    image: "https://m.media-amazon.com/images/I/61sG5z1cNzL._AC_SY679_.jpg",
  },
  {
    title: "The Dark Knight Rises",
    rate: 8.4,
    year: 2012,
    image: "https://m.media-amazon.com/images/I/51EbJjlO1GL._AC_.jpg",
  },
  {
    title: "Django Unchained",
    rate: 8.4,
    year: 2012,
    image: "https://m.media-amazon.com/images/I/61X2yK00rnL._AC_SL1000_.jpg",
  },
  {
    title: "WALL·E",
    rate: 8.4,
    year: 2008,
    image: "https://m.media-amazon.com/images/I/81Bv9UdtG+L._AC_SL1500_.jpg",
  },
  {
    title: "The Lives of Others",
    rate: 8.4,
    year: 2006,
    image: "https://m.media-amazon.com/images/I/51ASZP-VKHL._AC_.jpg",
  },
  {
    title: "Parasite",
    rate: 8.5,
    year: 2019,
    image: "https://m.media-amazon.com/images/I/61uZHdbWuRL._AC_SY679_.jpg",
  },
  {
    title: "Joker",
    rate: 8.4,
    year: 2019,
    image: "https://m.media-amazon.com/images/I/71iU3LzDmvL._AC_SY679_.jpg",
  },
  {
    title: "Avengers: Infinity War",
    rate: 8.4,
    year: 2018,
    image: "https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg",
  },
  {
    title: "Avengers: Endgame",
    rate: 8.4,
    year: 2019,
    image: "https://m.media-amazon.com/images/I/81ai6zx6eXL._AC_SY679_.jpg",
  },
  {
    title: "Oldboy",
    rate: 8.4,
    year: 2003,
    image: "https://m.media-amazon.com/images/I/51iWEG69paL._AC_.jpg",
  },
  {
    title: "Coco",
    rate: 8.4,
    year: 2017,
    image: "https://m.media-amazon.com/images/I/81vpsIs58WL._AC_SY679_.jpg",
  },
  {
    title: "Your Name.",
    rate: 8.4,
    year: 2016,
    image: "https://m.media-amazon.com/images/I/61P1Jd5C3IL._AC_SY741_.jpg",
  },
];


