export const movieTypes = [
  "Action",
  "Adventure",
  "Animation",
  "Children's",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Film-Noir",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
  "Western"
];

export const movies = [
  {
    title: "The Shawshank Redemption",
    rate: 9.3,
    year: 1994,
    src: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    theme: "Sci-Fi",
  },
  {
    title: "The Godfather",
    rate: 9.2,
    year: 1972,
    src: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    theme: "Romance",
  },
  {
    title: "The Dark Knight",
    rate: 9.0,
    year: 2008,
    src: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    theme: "Comedy",
  },
  {
    title: "The Godfather Part II",
    rate: 9.0,
    year: 1974,
    src: "https://image.tmdb.org/t/p/w500/amvmeQWheahG3StKwIE1f7jRnkZ.jpg",
    theme: "Musical",
  },
  {
    title: "12 Angry Men",
    rate: 9.0,
    year: 1957,
    src: "https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    theme: "Documentary",
  },
  {
    title: "Schindler's List",
    rate: 8.9,
    year: 1993,
    src: "https://image.tmdb.org/t/p/w500/c8Ass7acuOe4za6DhSattE359gr.jpg",
    theme: "Western",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    rate: 8.9,
    year: 2003,
    src: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    theme: "Children's",
  },
  {
    title: "Pulp Fiction",
    rate: 8.9,
    year: 1994,
    src: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    theme: "Thriller",
  },
  {
    title: "The Good, the Bad and the Ugly",
    rate: 8.8,
    year: 1966,
    src: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    theme: "Fantasy",
  },
  {
    title: "Forrest Gump",
    rate: 8.8,
    year: 1994,
    src: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    theme: "Western",
  },
  {
    title: "Fight Club",
    rate: 8.8,
    year: 1999,
    src: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    theme: "Animation",
  },
  {
    title: "Inception",
    rate: 8.8,
    year: 2010,
    src: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    theme: "Sci-Fi",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    rate: 8.8,
    year: 2001,
    src: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    theme: "Drama",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    rate: 8.7,
    year: 1980,
    src: "https://image.tmdb.org/t/p/w500/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
    theme: "Action",
  },
  {
    title: "The Matrix",
    rate: 8.7,
    year: 1999,
    src: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    theme: "Sci-Fi",
  },
  {
    title: "Goodfellas",
    rate: 8.7,
    year: 1990,
    src: "https://image.tmdb.org/t/p/w500/6QMSLvU5ziIL2T6VrkaKzN2YkxK.jpg",
    theme: "Crime",
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    rate: 8.7,
    year: 1975,
    src: "https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
    theme: "Mystery",
  },
  {
    title: "Se7en",
    rate: 8.6,
    year: 1995,
    src: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    theme: "Thriller",
  },
  {
    title: "It's a Wonderful Life",
    rate: 8.6,
    year: 1946,
    src: "https://image.tmdb.org/t/p/w500/bRz2cAYiR5oYRTb2nX2h9tQbK1D.jpg",
    theme: "Drama",
  },
  {
    title: "Seven Samurai",
    rate: 8.6,
    year: 1954,
    src: "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    theme: "War",
  },
];




